import { createContext, useContext, useState } from "react";

export const translations = {
  SPA: {
    screensaver: {
      hint: "Toca la pantalla para comenzar",
    },
    welcome: {
      title: "Bienvenido",
      start: "Comenzar",
      loginTitle: "Iniciar sesión",
      loginSub: "Escaneá tu app y sumá puntos",
      loginHint: "Abrí la app y mostrá tu código",
      continueGuest: "Continuar sin\niniciar sesión",
      welcomeBack: "¡Bienvenido de nuevo,",
      scanning: "Leyendo código...",
    },
    orderType: {
      title: "Seleccione una opción",
      here: "Comer aquí",
      takeaway: "Para llevar",
    },
    home: {
      back: "VOLVER",
      here: "Comer aquí",
      takeaway: "Para llevar",
      offerTitle: "OFERTA ESPECIAL",
      offerTimer: "⏱ Oferta por tiempo limitado",
      viewOffer: "VER OFERTA →",
      myOrder: "MI ORDEN",
      emptyOrder: "Por el momento tu orden esta vacía ...",
      product: "producto",
      products: "productos",
      cancelOrder: "CANCELAR ORDEN",
      viewOrder: "VER PEDIDO",
      coupon: "TENGO UN CUPÓN",
      promoAlt: "Promo del día",
      search: "Buscar producto...",
      addToOrder: "Añadir al pedido",
      applyCoupon: "APLICAR CUPÓN",
      includes: "Incluye:",
      description: "Descripción",
      ingredients: "Ingredientes",
      reviews: "reseñas",
    },
    cart: {
      title: "Mi Pedido",
      subtotal: "Subtotal",
      confirm: "CONFIRMAR PEDIDO",
      keepBrowsing: "Seguir explorando",
      confirmed: "¡Pedido recibido!",
      confirmedSub: "Tu pedido está siendo preparado",
    },
    idle: {
      title: "¿Seguís ahí?",
      sub: "Tu sesión se cancelará automáticamente",
      continue: "Sí, continuar",
    },
    upsell: {
      added: "agregado al pedido",
      title: "¿Querés agregar algo más?",
      add: "Agregar",
      noThanks: "No gracias, continuar",
    },
    orderConfirmed: {
      title: "¡Pedido recibido!",
      number: "Pedido",
      preparing: "Está siendo preparado con amor",
      wait: "En breve estará listo para vos",
      returnIn: "Volviendo al inicio en",
      seconds: "segundos",
      paymentMethod: "Forma de pago",
    },
    payment: {
      title: "¿Cómo vas a pagar?",
      cash: "Efectivo",
      card: "Tarjeta",
      qr: "QR / Mercado Pago",
    },
    categories: {
      TODOS: "Todos",
      ENSALADAS: "Ensaladas",
      BURGERS: "Burgers",
      EMPLATADOS: "Emplatados",
      SANDWICHS: "Sandwichs",
      PROMOS: "Promos",
      PIZZAS: "Pizzas",
      PASTAS: "Pastas",
      POSTRES: "Postres",
      HELADOS: "Helados",
      BEBIDAS: "Bebidas",
      CUPONES: "Cupones",
    },
  },

  ENG: {
    screensaver: {
      hint: "Touch the screen to start",
    },
    welcome: {
      title: "Welcome",
      start: "Start",
      loginTitle: "Sign in",
      loginSub: "Scan your app and earn points",
      loginHint: "Open the app and show your code",
      continueGuest: "Continue without\nsigning in",
      welcomeBack: "Welcome back,",
      scanning: "Reading code...",
    },
    orderType: {
      title: "Select an option",
      here: "Dine in",
      takeaway: "Take away",
    },
    home: {
      back: "BACK",
      here: "Dine in",
      takeaway: "Take away",
      offerTitle: "SPECIAL OFFER",
      offerTimer: "⏱ Limited time offer",
      viewOffer: "VIEW OFFER →",
      myOrder: "MY ORDER",
      emptyOrder: "Your order is currently empty ...",
      product: "item",
      products: "items",
      cancelOrder: "CANCEL ORDER",
      viewOrder: "VIEW ORDER",
      coupon: "I HAVE A COUPON",
      promoAlt: "Daily special",
      search: "Search...",
      addToOrder: "Add to order",
      applyCoupon: "APPLY COUPON",
      includes: "Includes:",
      description: "Description",
      ingredients: "Ingredients",
      reviews: "reviews",
    },
    cart: {
      title: "My Order",
      subtotal: "Subtotal",
      confirm: "CONFIRM ORDER",
      keepBrowsing: "Keep browsing",
      confirmed: "Order received!",
      confirmedSub: "Your order is being prepared",
    },
    idle: {
      title: "Still there?",
      sub: "Your session will be cancelled automatically",
      continue: "Yes, continue",
    },
    upsell: {
      added: "added to order",
      title: "Want to add something else?",
      add: "Add",
      noThanks: "No thanks, continue",
    },
    orderConfirmed: {
      title: "Order received!",
      number: "Order",
      preparing: "Being lovingly prepared",
      wait: "It will be ready shortly",
      returnIn: "Returning to home in",
      seconds: "seconds",
      paymentMethod: "Payment method",
    },
    payment: {
      title: "How will you pay?",
      cash: "Cash",
      card: "Card",
      qr: "QR / Mercado Pago",
    },
    categories: {
      TODOS: "All",
      ENSALADAS: "Salads",
      BURGERS: "Burgers",
      EMPLATADOS: "Plates",
      SANDWICHS: "Sandwiches",
      PROMOS: "Promos",
      PIZZAS: "Pizzas",
      PASTAS: "Pasta",
      POSTRES: "Desserts",
      HELADOS: "Ice Cream",
      BEBIDAS: "Drinks",
      CUPONES: "Coupons",
    },
  },

  PRT: {
    screensaver: {
      hint: "Toque a tela para começar",
    },
    welcome: {
      title: "Bem-vindo",
      start: "Começar",
      loginTitle: "Entrar",
      loginSub: "Escaneie seu app e acumule pontos",
      loginHint: "Abra o app e mostre seu código",
      continueGuest: "Continuar sem\nentrar",
      welcomeBack: "Bem-vindo de volta,",
      scanning: "Lendo código...",
    },
    orderType: {
      title: "Selecione uma opção",
      here: "Comer aqui",
      takeaway: "Para viagem",
    },
    home: {
      back: "VOLTAR",
      here: "Comer aqui",
      takeaway: "Para viagem",
      offerTitle: "OFERTA ESPECIAL",
      offerTimer: "⏱ Oferta por tempo limitado",
      viewOffer: "VER OFERTA →",
      myOrder: "MEU PEDIDO",
      emptyOrder: "Seu pedido está vazio por enquanto ...",
      product: "produto",
      products: "produtos",
      cancelOrder: "CANCELAR PEDIDO",
      viewOrder: "VER PEDIDO",
      coupon: "TENHO UM CUPOM",
      promoAlt: "Promoção do dia",
      search: "Pesquisar...",
      addToOrder: "Adicionar ao pedido",
      applyCoupon: "APLICAR CUPOM",
      includes: "Inclui:",
      description: "Descrição",
      ingredients: "Ingredientes",
      reviews: "avaliações",
    },
    cart: {
      title: "Meu Pedido",
      subtotal: "Subtotal",
      confirm: "CONFIRMAR PEDIDO",
      keepBrowsing: "Continuar navegando",
      confirmed: "Pedido recebido!",
      confirmedSub: "Seu pedido está sendo preparado",
    },
    idle: {
      title: "Ainda está aí?",
      sub: "Sua sessão será cancelada automaticamente",
      continue: "Sim, continuar",
    },
    upsell: {
      added: "adicionado ao pedido",
      title: "Quer adicionar mais alguma coisa?",
      add: "Adicionar",
      noThanks: "Não obrigado, continuar",
    },
    orderConfirmed: {
      title: "Pedido recebido!",
      number: "Pedido",
      preparing: "Sendo preparado com carinho",
      wait: "Ficará pronto em breve",
      returnIn: "Voltando ao início em",
      seconds: "segundos",
      paymentMethod: "Forma de pagamento",
    },
    payment: {
      title: "Como vai pagar?",
      cash: "Dinheiro",
      card: "Cartão",
      qr: "QR / Mercado Pago",
    },
    categories: {
      TODOS: "Todos",
      ENSALADAS: "Saladas",
      BURGERS: "Burgers",
      EMPLATADOS: "Pratos",
      SANDWICHS: "Sanduíches",
      PROMOS: "Promoções",
      PIZZAS: "Pizzas",
      PASTAS: "Massas",
      POSTRES: "Sobremesas",
      HELADOS: "Sorvetes",
      BEBIDAS: "Bebidas",
      CUPONES: "Cupons",
    },
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("SPA");
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
